# vim:ft=lf

cmd fzf-cd ${{
	lf -remote "send $id cd \"$(dirname "$(fzf)")\""
}}

cmd touch %{{
	IFS=" "
	file="$*"
	touch -- "$file"
	lf -remote "send $id select \"$file\""
}}

cmd mkdir %{{
	IFS=" "
	file="$*"
	mkdir -p -- "$file"
	lf -remote "send $id select \"$file\""
}}

cmd trash-put ${{
	set -f
	printf "$fx\ntrash?[y/n]\n"
	read ans
	[ "$ans" = "y" ] && trash-put $fx
}}
