# vim:ft=lf

map ','
map 'y'
map 'd'

map ,. cd ~/
map <gt> $$EDITOR
map . $$SHELL
map aa push :touch<space>
map ad push :mkdir<space>
map zd fzf-cd

map yy copy
map dd cut
map dD trash-put
map dx delete
