#!/bin/sh

mod=Super

alias map='riverctl map'

map normal $mod Z             zoom
map normal $mod S             toggle-float
map normal $mod F             toggle-fullscreen
map normal $mod Return        spawn foot
map normal $mod Q             close
map normal $mod D             spawn 'wmenu-color wmenu-run'
map normal $mod Semicolon     spawn 'menu-clip'
map normal $mod W             spawn 'selwall'
map normal ${mod}+Shift W     spawn 'wooz --invert-scroll --map-close q'
map normal ${mod}+Control L   spawn 'lockscreen'
map normal ${mod}+Shift Q     exit

# screenshot
map normal $mod         C     spawn 'screenshot -s -c'
map normal $mod         Print spawn 'screenshot -a -c'
map normal ${mod}+Shift C     spawn 'screenshot -s -f'
map normal ${mod}+Shift Print spawn 'screenshot -a -f'

map -repeat normal $mod         J      focus-view     next
map -repeat normal $mod         K      focus-view     previous
map -repeat normal ${mod}+Shift J      swap           next
map -repeat normal ${mod}+Shift K      swap           previous
map -repeat normal $mod         Period focus-output   next
map -repeat normal $mod         Comma  focus-output   previous
map -repeat normal ${mod}+Shift Period send-to-output next
map -repeat normal ${mod}+Shift Comma  send-to-output previous
map -repeat normal ${mod}+Alt H move left 100
map -repeat normal ${mod}+Alt J move down 100
map -repeat normal ${mod}+Alt K move up 100
map -repeat normal ${mod}+Alt L move right 100
map -repeat normal ${mod}+Alt+Shift H resize horizontal -100
map -repeat normal ${mod}+Alt+Shift J resize vertical 100
map -repeat normal ${mod}+Alt+Shift K resize vertical -100
map -repeat normal ${mod}+Alt+Shift L resize horizontal 100
map normal ${mod}+Alt+Control H snap left
map normal ${mod}+Alt+Control J snap down
map normal ${mod}+Alt+Control K snap up
map normal ${mod}+Alt+Control L snap right
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    map normal $mod $i set-focused-tags $tags
    map normal ${mod}+Shift $i set-view-tags $tags
    map normal ${mod}+Control $i toggle-focused-tags $tags
    map normal ${mod}+Shift+Control $i toggle-view-tags $tags
done
all_tags=$(((1 << 32) - 1))
map normal $mod 0 set-focused-tags $all_tags
map normal ${mod}+Shift 0 set-view-tags $all_tags

# media contrl
map normal ${mod}+Shift M spawn mpdaction
map normal ${mod}+Shift G spawn 'getvol -n'
for mode in normal locked
do
    map $mode ${mod}+Alt Up   spawn 'setvol -u'
    map $mode ${mod}+Alt Down spawn 'setvol -d'

    map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set 5%+'
    map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'

    map $mode None XF86AudioRaiseVolume  spawn 'setvol -u'
    map $mode None XF86AudioLowerVolume  spawn 'setvol -d'
done

map normal $mod M     send-layout-cmd rivercarro 'main-location monocle'
map normal $mod Up    send-layout-cmd rivercarro 'main-location top'
map normal $mod Right send-layout-cmd rivercarro 'main-location right'
map normal $mod Down  send-layout-cmd rivercarro 'main-location bottom'
map normal $mod Left  send-layout-cmd rivercarro 'main-location left'
map -repeat normal $mod H send-layout-cmd rivercarro 'main-ratio -0.05'
map -repeat normal $mod L send-layout-cmd rivercarro 'main-ratio +0.05'
map -repeat normal ${mod}+Shift H send-layout-cmd rivercarro 'main-count +1'
map -repeat normal ${mod}+Shift L send-layout-cmd rivercarro 'main-count -1'

# warpd
map normal $mod X spawn 'warpd --normal'
map normal $mod G spawn 'warpd --grid'
