#!/bin/sh

mod=Super

riverctl map normal ${mod}+Shift Q exit

riverctl map normal $mod Return spawn foot
riverctl map normal $mod Q close
riverctl map normal $mod D spawn 'wmenu-color wmenu-run'
riverctl map normal $mod Semicolon spawn 'menu-clip'
riverctl map normal $mod W spawn 'swayimg -a float -g $HOME/Pictures/wallpaper'
riverctl map normal ${mod}+Shift '*' spawn 'lockscreen'

# screenshot
riverctl map normal $mod C spawn 'screenshot -s -c'
riverctl map normal $mod Print spawn 'screenshot -a -c'
riverctl map normal ${mod}+Shift C spawn 'screenshot -s -f'
riverctl map normal ${mod}+Shift Print spawn 'screenshot -a -f'

riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous
riverctl map normal ${mod}+Shift J swap next
riverctl map normal ${mod}+Shift K swap previous

riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous
riverctl map normal ${mod}+Shift Period send-to-output next
riverctl map normal ${mod}+Shift Comma send-to-output previous

riverctl map normal $mod Z zoom
riverctl map normal $mod S toggle-float
riverctl map normal $mod F toggle-fullscreen

riverctl map normal $mod H send-layout-cmd rivertile 'main-ratio -0.05'
riverctl map normal $mod L send-layout-cmd rivertile 'main-ratio +0.05'
riverctl map normal ${mod}+Shift H send-layout-cmd rivertile 'main-count +1'
riverctl map normal ${mod}+Shift L send-layout-cmd rivertile 'main-count -1'
riverctl map normal ${mod}+Alt H move left 100
riverctl map normal ${mod}+Alt J move down 100
riverctl map normal ${mod}+Alt K move up 100
riverctl map normal ${mod}+Alt L move right 100
riverctl map normal ${mod}+Alt+Control H snap left
riverctl map normal ${mod}+Alt+Control J snap down
riverctl map normal ${mod}+Alt+Control K snap up
riverctl map normal ${mod}+Alt+Control L snap right
riverctl map normal ${mod}+Alt+Shift H resize horizontal -100
riverctl map normal ${mod}+Alt+Shift J resize vertical 100
riverctl map normal ${mod}+Alt+Shift K resize vertical -100
riverctl map normal ${mod}+Alt+Shift L resize horizontal 100
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal ${mod}+Shift $i set-view-tags $tags
    riverctl map normal ${mod}+Control $i toggle-focused-tags $tags
    riverctl map normal ${mod}+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal ${mod}+Shift 0 set-view-tags $all_tags
riverctl map normal $mod Up    send-layout-cmd rivertile 'main-location top'
riverctl map normal $mod Right send-layout-cmd rivertile 'main-location right'
riverctl map normal $mod Down  send-layout-cmd rivertile 'main-location bottom'
riverctl map normal $mod Left  send-layout-cmd rivertile 'main-location left'

# media contrl
riverctl map normal ${mod}+Shift M spawn mpdaction
riverctl map normal ${mod} G spawn 'getvol -n'
for mode in normal locked
do
    riverctl map $mode ${mod}+Alt Up   spawn 'setvol -u'
    riverctl map $mode ${mod}+Alt Down spawn 'setvol -d'

    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set 5%+'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'

    riverctl map $mode None XF86AudioRaiseVolume  spawn 'setvol -u'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'setvol -d'
done
