#!/bin/sh

wl_paste_text="wl-paste --type text --watch cliphist store"
wl_paste_image="wl-paste --type image --watch cliphist store"

killall -q fcitx5

riverctl spawn "fcitx5 -d"

pgrep "sfcp" || riverctl spawn "sfcp"
pgrep "swayidle" || riverctl spawn "swayidle"
pgrep -f "$wl_paste_text" || riverctl spawn "$wl_paste_text"
pgrep -f "$wl_paste_image" || riverctl spawn "$wl_paste_image"
pgrep "mako" || riverctl spawn "mako"

riverctl map normal Super Return spawn foot

if [ -f "$HOME/Pictures/wallpaper/default" ]; then
	setwall "$HOME/Pictures/wallpaper/default"
fi

source $HOME/.config/river/bindings
source $HOME/.config/river/settings
