#!/bin/sh

riverctl background-color 0x000000
riverctl border-color-focused 0xa3a3a3
riverctl border-color-unfocused 0x000000
riverctl border-width 0
riverctl set-repeat 50 300
riverctl focus-follows-cursor normal
riverctl rule-add -app-id 'float*' float
riverctl rule-add -app-id 'QQ' float
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 &
