# -*- conf -*-
# vim:foldmethod=marker

include=~/.config/foot/color-solarized-dark.ini
include=~/.config/foot/color-solarized-light.ini
#term=xterm-256color
#font=SauceCodePro Nerd Font Mono:size=12
#font=Maple Mono Normal NL NF CN:size=12
font=Unifont:pixelsize=16
#font=Iosevka Term:style=Medium:size=14

[cursor]
blink=yes

#[url]
#launch=qutebrowser ${url}


[key-bindings]
scrollback-up-half-page=Control+Shift+k
scrollback-down-half-page=Control+Shift+j
show-urls-launch=Control+Shift+f
show-urls-copy=Control+Shift+y
color-theme-toggle=Control+Shift+s

# vim: ft=dosini
