monitor=,preferred,auto,auto

source=theme.conf

exec-once = waybar
exec-once = fcitx5
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = systemctl --user start hyprpolkitagent
exec-once = ~/.local/bin/wallpaperd.sh

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

input {
	sensitivity = 0.0
}

source=bindings.conf

windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = float, class:QQ
#windowrule = size 1280,720 center, class:neovide, floating:1
