source=catppuccin/themes/mocha.conf

general {
	border_size = 2
	gaps_in  = 5
	gaps_out = 5
	col.inactive_border = $base
	col.active_border = $maroon
}

decoration {
	rounding = 5
	rounding_power = 2
	inactive_opacity = 0.8
	dim_inactive = false
	blur {
		enabled = false
	}
}

group {
	col.border_active = $pink
	col.border_inactive = $base
	groupbar {
		rounding = 0
		gradients = true
		gradient_rounding = 0
		indicator_height = 0
		text_color = $pink
		col.active = $surface2
		col.inactive = $base
		gaps_in  = 0
		gaps_out = 2
	}
}

misc {
	animate_mouse_windowdragging = true
}
